/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.citizen.app.cpcl;

public final class R {
    public static final class array {
        public static final int aligns=0x7f040000;
        public static final int msr_track=0x7f040001;
        public static final int sizes=0x7f040002;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int ButtonConnectBT=0x7f070002;
        public static final int ButtonConnectIP=0x7f07000a;
        public static final int ButtonSearchBT=0x7f070004;
        public static final int EditTextAddressBT=0x7f070001;
        public static final int EditTextAddressIP=0x7f070009;
        public static final int EditTextPopup=0x7f070007;
        public static final int LinearLayout01=0x7f070003;
        public static final int LinearLayout02=0x7f070005;
        public static final int LinearLayout03=0x7f070000;
        public static final int ListView01=0x7f070006;
        public static final int cancel=0x7f07000e;
        public static final int deleteall=0x7f07000d;
        public static final int ipList=0x7f07000c;
        public static final int linearLayout1=0x7f070008;
        public static final int linearLayout2=0x7f07000b;
    }
    public static final class layout {
        public static final int bluetooth_menu=0x7f030000;
        public static final int input_popup=0x7f030001;
        public static final int sample_menu=0x7f030002;
        public static final int tabbed_menu=0x7f030003;
        public static final int wifi_menu=0x7f030004;
    }
    public static final class menu {
        public static final int menu=0x7f060000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int bt_conn_fail_msg=0x7f050001;
        public static final int bt_conn_msg=0x7f050002;
        public static final int bt_disconn_msg=0x7f050003;
        public static final int bt_notconn_msg=0x7f050004;
        public static final int bt_search_btn=0x7f050005;
        public static final int bt_stop_search_btn=0x7f050006;
        public static final int bt_tab=0x7f050007;
        public static final int connecting_msg=0x7f050008;
        public static final int dev_check_msg=0x7f050009;
        public static final int dev_conn_btn=0x7f05000a;
        public static final int dev_disconn_btn=0x7f05000b;
        public static final int wifi_conn_fail_msg=0x7f05000c;
        public static final int wifi_conn_msg=0x7f05000d;
        public static final int wifi_disconn_msg=0x7f05000e;
        public static final int wifi_notconn_msg=0x7f05000f;
        public static final int wifi_tab=0x7f050010;
    }
}
